FROM apache/airflow:latest

RUN pip install --no-cache-dir apache-airflow-providers-docker \
    apache-airflow-providers-google \
    psycopg2-binary \
    pyyaml \
    google-cloud-bigquery \
    google-auth \
    pandas \
    requests \
    pytz \
    google-api-core